/// Channel keypairs (docs/protocol.md "E2E payloads" + "Channel key
/// distribution"): generated once by a channel's first user, distributed to
/// members as an E2E "chankey" DM, persisted in the machine-shared file
/// `~/.dap/channels.json` as `{ "<channel>": {"pub","priv"} }` (b64 X25519).
library;

import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';

/// One channel's X25519 keypair (base64).
class ChannelKeys {
  const ChannelKeys({required this.pub, required this.priv});

  final String pub;
  final String priv;
}

/// Fresh channel X25519 keypair — generated by the channel's first user.
Future<ChannelKeys> newChannelKeypair() async {
  final pair = await X25519().newKeyPair();
  final priv = await pair.extractPrivateKeyBytes();
  final pub = await pair.extractPublicKey();
  return ChannelKeys(pub: base64Encode(pub.bytes), priv: base64Encode(priv));
}

/// Channels file → keypairs. Missing or invalid file = no channels; only
/// entries with both keys survive.
Future<Map<String, ChannelKeys>> loadChannelKeys(String file) async {
  try {
    final raw = jsonDecode(await File(file).readAsString());
    if (raw is! Map) return {};
    final out = <String, ChannelKeys>{};
    for (final entry in raw.entries) {
      final keys = entry.value;
      if (keys is Map &&
          keys['pub'] is String &&
          keys['priv'] is String) {
        out[entry.key.toString()] =
            ChannelKeys(pub: keys['pub'] as String, priv: keys['priv'] as String);
      }
    }
    return out;
  } on Object {
    return {};
  }
}

/// Read-modify-write: keeps the other channels; creates the parent dir
/// (e.g. ~/.dap) on demand.
Future<void> persistChannelKeys(
    String file, String name, ChannelKeys keys) async {
  final all = await loadChannelKeys(file);
  all[name] = keys;
  final parent = File(file).parent;
  if (!await parent.exists()) await parent.create(recursive: true);
  final encoded = const JsonEncoder.withIndent('  ').convert({
    for (final entry in all.entries)
      entry.key: {'pub': entry.value.pub, 'priv': entry.value.priv},
  });
  await File(file).writeAsString('$encoded\n', flush: true);
}

/// A DM whose decrypted text is exactly a channel-invite payload
/// `{"t":"chankey","channel","pub","priv"}`. Regular chat that happens to
/// start with `{` still fails the shape check and returns null.
({String channel, String pub, String priv})? parseChankeyInvite(String text) {
  if (!text.startsWith('{')) return null;
  final Object? decoded;
  try {
    decoded = jsonDecode(text);
  } on FormatException {
    return null;
  }
  if (decoded is! Map) return null;
  if (decoded['t'] != 'chankey') return null;
  final channel = decoded['channel'];
  final pub = decoded['pub'];
  final priv = decoded['priv'];
  if (channel is! String || pub is! String || priv is! String) return null;
  try {
    if (base64Decode(pub).length != 32 || base64Decode(priv).length != 32) {
      return null;
    }
  } on FormatException {
    return null;
  }
  return (channel: channel, pub: pub, priv: priv);
}

/// Runtime channel-key state for one client: seeded from the shared
/// channels file, mutated by auto-keygen and accepted invites, persisted
/// read-modify-write. The hub never sees any of these keys (only public
/// keys via `join`).
class ChannelStore {
  ChannelStore._(this._file, Map<String, ChannelKeys> initial)
      : _keys = Map.of(initial);

  final String? _file;
  final Map<String, ChannelKeys> _keys;

  /// Loads the shared channels file (missing/invalid = empty).
  static Future<ChannelStore> fromFile(String file) async =>
      ChannelStore._(file, await loadChannelKeys(file));

  /// Known channels (for auto-join after each welcome).
  Map<String, ChannelKeys> get all => Map.unmodifiable(_keys);

  bool knows(String channel) => _keys.containsKey(channel);

  String? pubOf(String channel) => _keys[channel]?.pub;

  String? privOf(String channel) => _keys[channel]?.priv;

  /// Keys for [channel], generating + persisting a fresh keypair on first
  /// use (zero-config channel creation).
  Future<ChannelKeys> keysFor(String channel) async {
    final existing = _keys[channel];
    if (existing != null) return existing;
    final created = await newChannelKeypair();
    _keys[channel] = created;
    await _persist(channel, created);
    return created;
  }

  /// Persists an invited keypair (possession of the channel private key IS
  /// v1 membership; the introducer is whoever DM'd you — same trust as
  /// manually sharing the file).
  Future<void> accept(String channel, ChannelKeys keys) async {
    _keys[channel] = keys;
    await _persist(channel, keys);
  }

  Future<void> _persist(String channel, ChannelKeys keys) async {
    final file = _file;
    if (file != null) await persistChannelKeys(file, channel, keys);
  }
}
